version: '3'

services:

  joomla:
    image: joomla
    restart: always
    depends_on:
       - joomladbos
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: joomladbos
      JOOMLA_DB_USER: user
      JOOMLA_DB_PASSWORD: password
      JOOMLA_DB_NAME: mydb
    volumes:
      - jm_db:/var/www/html
     
  joomladbos:
    image: mariadb
    volumes:
      - maria_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
      

volumes:
   maria_db:
   jm_db:
